missing-paws/config/routes.rb
Rails.application.routes.draw do    
  get 'sessions/new'

  get 'users/new'

  get 'home/index'
  get 'news/index'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  scope '(:locale)', locale:/en|de/ do

    resources :articles
    resources :adoptions
    resources :found_animals
    resources :lost_animals
    resources :topics
    resources :vet_centers
    resources :animal_shelters
    resources :pet_shops
    resources :pet_academies
    resources :pet_hotels
    resources :users
    resources :forums do
      resources :forum_comments 
    end 

    root to: 'articles#index'
  end

end

missing-paws/app/views/layouts/_aside.html.erb
<aside class="col-sm-4">

  <h1 class="text-right"><%= t('.recent') || "Recent" %></h1>

  <div class="recent-item" class="row">

    <h3 class="text-center"><%= t('.lost') || "Lost" %></h3>

    <%= image_tag(LostAnimal.order("created_at").last.image) %>


    <h4><a href="/lost_animals"><%= LostAnimal.order("created_at").last.title %></a></h4>

    <div class="corner"></div>
    <div class="clearfix"></div>

  </div>

  <div class="recent-item" class="row">

    <h3 class="text-center"><%= t('.found') || "Found" %></h3>

    <%= image_tag(FoundAnimal.order("created_at").last.image) %>


    <h4><a href="/found_animals"><%= FoundAnimal.order("created_at").last.title %></a></h4>

    <div class="corner"></div>
    <div class="clearfix"></div>

  </div>

  <div class="recent-item" class="row">

    <h3 class="text-center"><%= t('.adoption') || "Adoption" %></h3>

    <%= image_tag(Adoption.order("created_at").last.image) %>


    <h4><a href="/adoptions"><%= Adoption.order("created_at").last.title %></a></h4>

    <div class="corner"></div>
    <div class="clearfix"></div>

  </div>

  <div class="recent-item" class="row">

    <h3 class="text-center"><%= t('.petcyclopedia') || "Petcyclopedia" %></h3>

    <%= image_tag(Topic.order("RANDOM()").first.picture) %>


    <h4><a href="/topics/<%= Topic.order("RANDOM()").first.id %>"><%= Topic.order("RANDOM()").first.title %></a></h4>

    <div class="corner"></div>
    <div class="clearfix"></div>

  </div>

  <div class="recent-item">
    <h3><%= t('.follow-us') || "Follow us" %></h3>
    <!--  code for facebook page starts here -->         
    <div class="fb-page" data-href="https://www.facebook.com/pages/Missing-Paws/937407539652514?skip_nax_wizard=true" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="true"></div>

    <div class="fb-xfbml-parse-ignore">
      <blockquote cite="https://www.facebook.com/pages/Missing-Paws/937407539652514?skip_nax_wizard=true">
        <a href="https://www.facebook.com/pages/Missing-Paws/937407539652514?skip_nax_wizard=true">Missing Paws</a>
      </blockquote>
    </div>
    <!--  code for facebook page ends here --> 

    <div class="corner"></div>
    <div class="clearfix"></div>

  </div>

</aside>

missing-paws/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>MissingPaws</title>

  <!-- Include all stylesheets -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <!-- Include add scripts -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Set page encoding -->
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">

  <!-- Set rendering engine for old IE versions -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <!-- Set viewport width for responsive design -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Add custom fond -->
  <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700" rel='stylesheet' type='text/css'>

</head>
<body>

  <div class="container" id="main-wrapper">

    <header class="row">

      <nav class="navbar navbar-default navbar-fixed-top">

        <div class="container">

          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only"><%= t('.toggle-nav') || 'Toggle navigation' %></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <!--<a class="navbar-brand" href="#">Missing paws</a>-->
            <%= link_to image_tag("Logo2.png"), articles_path, class: 'navbar-brand' %>
          </div>

          <div id="navbar" class="navbar-collapse collapse">

            <ul class="nav navbar-default navbar-nav">

              <li class="<%= 'active' if params[:controller] == 'lost_animals' %>">         
                <%= link_to t('.lost-animals'), lost_animals_path %>
              </li>

              <li class="<%= 'active' if params[:controller] == 'found_animals' %>">            
                <%= link_to t('.found-animals'), found_animals_path %>
              </li>

              <li class="<%= 'active' if params[:controller] == 'adoptions' %>">             
                <%= link_to t('.adoptions'), adoptions_path %>
              </li>

              <li class="<%= 'active' if params[:controller] == 'topics' %>">
                <%= link_to t('.petcyclopedia'), topics_path %>
              </li>

              <li class="dropdown">

                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= t('.partners') %><span class="caret"></span></a>

                <ul class="dropdown-menu">
                  <li><%= link_to t('.vet-centers'), vet_centers_path %></li>
                  <li><%= link_to t('.animal-shelters'), animal_shelters_path %></li>
                  <li><%= link_to t('.pet-shops'), pet_shops_path %></li>
                  <li><%= link_to t('.pet-academy'), pet_academies_path %></li>
                  <li><%= link_to t('.pet-hotels'), pet_hotels_path %></li>
                </ul>
              </li>

              <li class="<%= 'active' if params[:controller] == 'forums' %>">
                <%= link_to t('.forum'), forums_path %>
              </li>
            </ul>

            <ul class="nav  navbar-default navbar-nav navbar-right">

              <li class="language-bar">
                <span>
                  <%= link_to image_tag("/images/germany-flag-icon.png"),(root_path(locale: :de))%>
                  <%= link_to image_tag("/images/UNITEDKINGDOM.gif"),(root_path(locale: :en))%>
                </span>
              </li>
              <% if logged_in? %>
              <% if current_user.try(:admin?) %>
              <li><%= link_to t('.users'), users_path %></li>
              <% end %>  
              
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= current_user.name %><b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to t('.profile'), current_user %></li>
                  <li><%= link_to t('.settings'), edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to t('.log-out'), logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
              <% else %>
              <li><%= link_to t('.log-in'), login_path %></li>
              <li><%= link_to t('.sign-up'), signup_path %></li>
              <% end %>   
            </ul>
          </div>

        </div> <!-- END of nav container -->

      </nav>

    </header>

    <div class="row" id="middle">
      <div class="container">

        <section class="<%= 'col-sm-8' unless @disable_aside %>" id="main-content">
          <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
          <%= yield %>
        </section>

        <%= render 'layouts/aside' unless @disable_aside %>
      </div>
    </div>
  </div>

  <footer class="row text-center">

    <div class="container">

      <div class="row">

        <div class="col-sm-2">
          <ul>
            <li><%= t('.nav') %></li>
            <li><a href="#">Home</a></li>
            <li><%= link_to t('.lost-animals'), lost_animals_path %></li>
            <li><%= link_to t('.found-animals'), found_animals_path %></li>
            <li><%= link_to t('.adoptions'), adoptions_path %></li>
            <li><%= link_to t('.petcyclopedia'), topics_path %></li>
          </ul>
        </div>

        <div class="col-sm-2">
          <ul>
            <li><%= t('.vet-centers') %></li>
            <li><a href="/vet_centers/1">Saint George</a></li>
            <li><a href="/vet_centers/2">Central Veterinary</a></li>
            <li><a href="/vet_centers/3">Clinic Sofia</a></li>
            <li><a href="/vet_centers/4">Clinic Nova</a></li>
            <li><a href="/vet_centers/5">Blue Cross</a></li>
          </ul>
        </div>

        <div class="col-sm-2">
          <ul>
            <li><%= t('.animal-shelters') %></li>
            <li><a href="/animal_shelters/1">Arsofia</a></li>
            <li><a href="/animal_shelters/2">Seslavtsi</a></li>
            <li><a href="/animal_shelters/3">Shelter "Gabrovo"</a></li>
            <li><a href="/animal_shelters/4">S O S - Animal</a></li>           
          </ul>
        </div>

        <div class="col-sm-2">
          <ul>
            <li><%= t('.pet-shops') %></li>
            <li><a href="/pet_shops/1">Jungle</a></li>           
            <li><a href="/pet_shops/2">BG Pet</a></li>           
            <li><a href="/pet_shops/3">ZOO Center</a></li>           
            <li><a href="/pet_shops/4">ZOO Mall</a></li>           
          </ul>
        </div>

        <div class="col-sm-2">
          <ul>
            <li><%= t('.pet-academy') %></li>
            <li><a href="/pet_academies/1">Obedient</a></li>
            <li><a href="/pet_academies/2">Ethan</a></li>
            <li><a href="/pet_academies/3">Black Ninja</a></li>
          </ul>
        </div>

        <div class="col-sm-2">
          <ul>
            <li><%= t('.pet-hotels') %></li>
            <li><a href="/pet_hotels/1">Earth dogs</a></li>
            <li><a href="/pet_hotels/2">Happiness</a></li>
            <li><a href="/pet_hotels/3">Best pets holiday</a></li>
            <li><a href="/pet_hotels/3">Caring for them</a></li>
          </ul>
        </div>
      </div>

      <div class="row" id="contacts">

        <div class="col-sm-6">
          <p><%= t('.contacts') %>:</p>
          <p><%= t('.phone') %>: <span class="underline">+359 894 405 432</span> | Email: <span class="underline">sample@mail.com</span></p>
        </div>

        <div class="col-sm-6">

          <a href="https://www.facebook.com/pages/Missing-Paws/937407539652514"><i id="social" class="fa fa-facebook-square fa-3x social-fb"></i></a>
          <a href="https://twitter.com/"><i id="social" class="fa fa-twitter-square fa-3x social-tw"></i></a>
          <a href="https://plus.google.com/"><i id="social" class="fa fa-google-plus-square fa-3x social-gp"></i></a>
          <a href="mailto:bootsnipp@gmail.com"><i id="social" class="fa fa-envelope-square fa-3x social-em"></i></a>

        </div>
      </div>

      <div class="row">

        <div class="col-sm-12" id="rights">
          <p>Missing paws &copy; 2015. All rights reserved.</p>
        </div>
      </div>

    </div>
  </footer>

  <!--Code for Facebook page -->
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/bg_BG/sdk.js#xfbml=1&version=v2.4";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
  <!-- END Code for Facebook page -->

</body>

</html>