missing-paws/config/routes.rb
Rails.application.routes.draw do    
  get 'sessions/new'

  get 'users/new'

  get 'home/index'
  get 'news/index'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  scope '(:locale)', locale:/en|de/ do

    resources :articles
    resources :adoptions
    resources :found_animals
    resources :lost_animals
    resources :topics
    resources :vet_centers
    resources :animal_shelters
    resources :pet_shops
    resources :pet_academies
    resources :pet_hotels
    resources :users
    resources :forums do
      resources :forum_comments 
    end 

    root to: 'articles#index'
  end

end

missing-paws/app/models/pet_hotel.rb
class PetHotel < ActiveRecord::Base

	belongs_to :user

	validates :user_id, presence: true
	def self.search(query)
		key = "%#{query}%"
		where("title LIKE :search OR description LIKE :search OR city LIKE :search", search: key)
	end 
end

missing-paws/app/controllers/pet_hotels_controller.rb
class PetHotelsController < ApplicationController
  before_action :set_pet_hotel, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:create, :destroy]

  # GET /pet_hotels
  # GET /pet_hotels.json
  def index
    if params[:search]
      @pet_hotels = PetHotel.search(params[:search]).order("created_at DESC")
    else
      @pet_hotels = PetHotel.all.order('created_at DESC')
    end 
  end

  # GET /pet_hotels/1
  # GET /pet_hotels/1.json
  def show
  end

  # GET /pet_hotels/new
  def new
    @pet_hotel = PetHotel.new
  end

  # GET /pet_hotels/1/edit
  def edit
  end

  # POST /pet_hotels
  # POST /pet_hotels.json
  def create

    @pet_hotel = current_user.pet_hotels.build(pet_hotel_params)

    respond_to do |format|
      if @pet_hotel.save
        format.html { redirect_to @pet_hotel, notice: I18n.t('.hotel-created') || 'Pet hotel was successfully created.' }
        format.json { render :show, status: :created, location: @pet_hotel }
      else
        format.html { render :new }
        format.json { render json: @pet_hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pet_hotels/1
  # PATCH/PUT /pet_hotels/1.json
  def update
    respond_to do |format|
      if @pet_hotel.update(pet_hotel_params)
        format.html { redirect_to @pet_hotel, notice: I18n.t('.hotel-updated') || 'Pet hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet_hotel }
      else
        format.html { render :edit }
        format.json { render json: @pet_hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pet_hotels/1
  # DELETE /pet_hotels/1.json
  def destroy
    @pet_hotel.destroy
    respond_to do |format|
      format.html { redirect_to pet_hotels_url, notice: I18n.t('.hotel-deleted') || 'Pet hotel was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet_hotel
      @pet_hotel = PetHotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_hotel_params
      params.require(:pet_hotel).permit(:title, :description, :image_url, :phone, :website, :city)
    end
end

missing-paws/app/helpers/pet_hotels_helper.rb
module PetHotelsHelper
end

missing-paws/app/views/pet_hotels/_form.html.erb
<%= form_for(@pet_hotel) do |f| %>
  <% if @pet_hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet_hotel.errors.count, "error") %> prohibited this pet_hotel from being saved:</h2>

      <ul>
      <% @pet_hotel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

missing-paws/app/views/pet_hotels/edit.html.erb
<h1>Editing Pet Hotel</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet_hotel %> |
<%= link_to 'Back', pet_hotels_path %>

missing-paws/app/views/pet_hotels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pet Hotels</h1>

<%= form_tag(pet_hotels_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], class: "search-field", placeholder: "Search"  %>
<%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
<% end %> 

<% if current_user.try(:admin?) %>
<%= link_to 'New Pet Hotel', new_pet_hotel_path, class: "btn btn-primary pull-right"%>
<% end %> 
<br>
<br>

<% @pet_hotels.each do |pet_hotel| %>

<div class="box">

  <div class="partner-box">
    <div class="image-wrapper">
      <%= image_tag(pet_hotel.image_url, class: 'list_image') %>
    </div>
    <div>
      <h3><a href="<%= pet_hotel.website%>"><%= pet_hotel.title %></a></h3>
    </div>
  </div>
  
  <div class="text-right">
    <% if current_user.try(:admin?) %>
    <%= link_to 'Edit', edit_pet_hotel_path(pet_hotel), class: 'btn btn-warning' %>
    <%= link_to 'Destroy', pet_hotel, class: 'btn btn-danger' , method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
</div>
<div class='animal_box'>
  <div class="top">
    <div>
      <button class='btn btn-default show-contacts'>More</button>
      <% if current_user.try(:admin?) || current_user?(pet_hotel.user) %>
      
      <% end %>
    </div>

  </div>

  <div class="bottom">

    <table class="table table-striped">
      <tr>
        <td><b>Title:</b></td>
        <td><%= pet_hotel.title %></td>
      </tr>
      <tr>
        <td><b>Phone:</b></td>
        <td><%= pet_hotel.phone %></td>
      </tr>
      <tr>
        <td><b>Website:</b></td>
        <td><%= pet_hotel.website %></td>
      </tr>
      <tr>
        <td><b>City:</b></td>
        <td><%= pet_hotel.city %></td>
      </tr>
      <tr>
        <td><b>Description:</b></td>
        <td><%= pet_hotel.description %></td>
      </tr>
      
    </table>
  </div>
</div>     

<% end %>

missing-paws/app/views/pet_hotels/new.html.erb
<h1>New Pet Hotel</h1>

<%= render 'form' %>

<%= link_to 'Back', pet_hotels_path %>

missing-paws/app/views/pet_hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @pet_hotel.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pet_hotel.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @pet_hotel.image_url %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @pet_hotel.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @pet_hotel.website %>
</p>

<p>
  <strong>City:</strong>
  <%= @pet_hotel.city %>
</p>

<%= link_to 'Edit', edit_pet_hotel_path(@pet_hotel) %> |
<%= link_to 'Back', pet_hotels_path %>