missing-paws/config/routes.rb
Rails.application.routes.draw do    
  get 'sessions/new'

  get 'users/new'

  get 'home/index'
  get 'news/index'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  scope '(:locale)', locale:/en|de/ do

    resources :articles
    resources :adoptions
    resources :found_animals
    resources :lost_animals
    resources :topics
    resources :vet_centers
    resources :animal_shelters
    resources :pet_shops
    resources :pet_academies
    resources :pet_hotels
    resources :users
    resources :forums do
      resources :forum_comments 
    end 

    root to: 'articles#index'
  end

end

missing-paws/app/models/animal_shelter.rb
class AnimalShelter < ActiveRecord::Base

	belongs_to :user

	validates :user_id, presence: true
	
	def self.search(query)
		key = "%#{query}%"
		where("title LIKE :search OR description LIKE :search OR city LIKE :search", search: key)
	end 
end

missing-paws/app/controllers/animal_shelters_controller.rb
class AnimalSheltersController < ApplicationController
  before_action :set_animal_shelter, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:create, :destroy]
  

  # GET /animal_shelters
  # GET /animal_shelters.json
  def index
    if params[:search]
      @animal_shelters = AnimalShelter.search(params[:search]).order("created_at DESC")
    else
      @animal_shelters = AnimalShelter.all.order('created_at DESC')
    end 
  end

  # GET /animal_shelters/1
  # GET /animal_shelters/1.json
  def show
  end

  # GET /animal_shelters/new
  def new
    @animal_shelter = AnimalShelter.new
  end

  # GET /animal_shelters/1/edit
  def edit
  end

  # POST /animal_shelters
  # POST /animal_shelters.json
  def create
    # @animal_shelter = AnimalShelter.new(animal_shelter_params)

    @animal_shelter = current_user.animal_shelters.build(animal_shelter_params)

    respond_to do |format|
      if @animal_shelter.save
        format.html { redirect_to @animal_shelter, notice: I18n.t('.shelter-created') || 'Animal shelter was successfully created.' }
        format.json { render :show, status: :created, location: @animal_shelter }
      else
        format.html { render :new }
        format.json { render json: @animal_shelter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animal_shelters/1
  # PATCH/PUT /animal_shelters/1.json
  def update
    respond_to do |format|
      if @animal_shelter.update(animal_shelter_params)
        format.html { redirect_to @animal_shelter, notice: I18n.t('.shelter-updated') || 'Animal shelter was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal_shelter }
      else
        format.html { render :edit }
        format.json { render json: @animal_shelter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animal_shelters/1
  # DELETE /animal_shelters/1.json
  def destroy
    @animal_shelter.destroy
    respond_to do |format|
      format.html { redirect_to animal_shelters_url, notice: I18n.t('.shelter-deleted') || 'Animal shelter was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal_shelter
      @animal_shelter = AnimalShelter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_shelter_params
      params.require(:animal_shelter).permit(:title, :description, :image_url, :phone, :website, :city)
    end
end

missing-paws/app/helpers/animal_shelters_helper.rb
module AnimalSheltersHelper
end

missing-paws/app/views/animal_shelters/_form.html.erb
<%= form_for(@animal_shelter) do |f| %>
  <% if @animal_shelter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animal_shelter.errors.count, "error") %> prohibited this animal_shelter from being saved:</h2>

      <ul>
      <% @animal_shelter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

missing-paws/app/views/animal_shelters/edit.html.erb
<h1>Editing Animal Shelter</h1>

<%= render 'form' %>

<%= link_to 'Show', @animal_shelter %> |
<%= link_to 'Back', animal_shelters_path %>

missing-paws/app/views/animal_shelters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Animal Shelters</h1>

<%= form_tag(animal_shelters_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], class: "search-field", placeholder: "Search"  %>
<%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
<% end %> 

<% if current_user.try(:admin?) %>
<%= link_to 'New Animal shelter', new_animal_shelter_path, class: "btn btn-primary pull-right"%>
<% end %> 
<br>
<br>

<% @animal_shelters.each do |animal_shelters| %>

<div class="box">

  <div class="partner-box">
    <div class="image-wrapper">
      <%= image_tag(animal_shelters.image_url, class: 'list_image') %>
    </div>
    <div>
      <h3><a href="<%= animal_shelters.website%>"><%= animal_shelters.title %></a></h3>
    </div>
  </div>
  
  <div class="text-right">
    <% if current_user.try(:admin?) %>
    <%= link_to 'Edit', edit_animal_shelter_path(animal_shelters), class: 'btn btn-warning' %>
    <%= link_to 'Destroy', animal_shelters, class: 'btn btn-danger' , method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
</div>

<div class='animal_box'>
  <div class="top">
    <div>
      <button class='btn btn-default show-contacts'>More</button>
      <% if current_user.try(:admin?) || current_user?(animal_shelters.user) %>
      
      <% end %>
    </div>

  </div>

  <div class="bottom">

    <table class="table table-striped">
      <tr>
        <td><b>Title:</b></td>
        <td><%= animal_shelters.title %></td>
      </tr>
      <tr>
        <td><b>Phone:</b></td>
        <td><%= animal_shelters.phone %></td>
      </tr>
      <tr>
        <td><b>Website:</b></td>
        <td><%= animal_shelters.website %></td>
      </tr>
      <tr>
        <td><b>City:</b></td>
        <td><%= animal_shelters.city %></td>
      </tr>
      <tr>
        <td><b>Description:</b></td>
        <td><%= animal_shelters.description %></td>
      </tr>
      
    </table>
  </div>
</div>     
<% end %>

missing-paws/app/views/animal_shelters/new.html.erb
<h1>New Animal Shelter</h1>

<%= render 'form' %>

<%= link_to 'Back', animal_shelters_path %>

missing-paws/app/views/animal_shelters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @animal_shelter.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @animal_shelter.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @animal_shelter.image_url %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @animal_shelter.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @animal_shelter.website %>
</p>

<p>
  <strong>City:</strong>
  <%= @animal_shelter.city %>
</p>

<%= link_to 'Edit', edit_animal_shelter_path(@animal_shelter) %> |
<%= link_to 'Back', animal_shelters_path %>