missing-paws/config/routes.rb
Rails.application.routes.draw do    
  get 'sessions/new'

  get 'users/new'

  get 'home/index'
  get 'news/index'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  scope '(:locale)', locale:/en|de/ do

    resources :articles
    resources :adoptions
    resources :found_animals
    resources :lost_animals
    resources :topics
    resources :vet_centers
    resources :animal_shelters
    resources :pet_shops
    resources :pet_academies
    resources :pet_hotels
    resources :users
    resources :forums do
      resources :forum_comments 
    end 

    root to: 'articles#index'
  end

end

missing-paws/app/models/pet_shop.rb
class PetShop < ActiveRecord::Base

	belongs_to :user

	validates :user_id, presence: true
	def self.search(query)
		key = "%#{query}%"
		where("title LIKE :search OR description LIKE :search OR city LIKE :search", search: key)
	end 
end

missing-paws/app/controllers/pet_shops_controller.rb
class PetShopsController < ApplicationController
  before_action :set_pet_shop, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:create, :destroy]
  

  # GET /pet_shops
  # GET /pet_shops.json
  def index
    if params[:search]
      @pet_shops = PetShop.search(params[:search]).order("created_at DESC")
    else
      @pet_shops = PetShop.all.order('created_at DESC')
    end 
  end

  # GET /pet_shops/1
  # GET /pet_shops/1.json
  def show
  end

  # GET /pet_shops/new
  def new
    @pet_shop = PetShop.new
  end

  # GET /pet_shops/1/edit
  def edit
  end

  # POST /pet_shops
  # POST /pet_shops.json
  def create

   @pet_shop = current_user.pet_shops.build(pet_shop_params)

    respond_to do |format|
      if @pet_shop.save
        format.html { redirect_to @pet_shop, notice: I18n.t('.shop-created') || 'Pet shop was successfully created.' }
        format.json { render :show, status: :created, location: @pet_shop }
      else
        format.html { render :new }
        format.json { render json: @pet_shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pet_shops/1
  # PATCH/PUT /pet_shops/1.json
  def update
    respond_to do |format|
      if @pet_shop.update(pet_shop_params)
        format.html { redirect_to @pet_shop, notice: I18n.t('.shop-updated') || 'Pet shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet_shop }
      else
        format.html { render :edit }
        format.json { render json: @pet_shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pet_shops/1
  # DELETE /pet_shops/1.json
  def destroy
    @pet_shop.destroy
    respond_to do |format|
      format.html { redirect_to pet_shops_url, notice: I18n.t('.shop-deleted') || 'Pet shop was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet_shop
      @pet_shop = PetShop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_shop_params
      params.require(:pet_shop).permit(:title, :description, :image_url, :phone, :website, :city)
    end
end

missing-paws/app/helpers/pet_shops_helper.rb
module PetShopsHelper
end

missing-paws/app/views/pet_shops/_form.html.erb
<%= form_for(@pet_shop) do |f| %>
  <% if @pet_shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet_shop.errors.count, "error") %> prohibited this pet_shop from being saved:</h2>

      <ul>
      <% @pet_shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

missing-paws/app/views/pet_shops/edit.html.erb
<h1>Editing Pet Shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet_shop %> |
<%= link_to 'Back', pet_shops_path %>

missing-paws/app/views/pet_shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pet Shops</h1>

<%= form_tag(pet_shops_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], class: "search-field", placeholder: "Search"  %>
<%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
<% end %> 

<% if current_user.try(:admin?) %>
<%= link_to 'New Pet Shop', new_pet_shop_path, class: "btn btn-primary pull-right"%>
<% end %> 
<br>
<br>

<% @pet_shops.each do |pet_shops| %>

<div class="box">

  <div class="partner-box">
    <div class="image-wrapper">
      <%= image_tag(pet_shops.image_url, class: 'list_image') %>
    </div>
    <div>
      <h3><a href="<%= pet_shops.website%>"><%= pet_shops.title %></a></h3>
    </div>
  </div>

  <div class="text-right">
    <% if current_user.try(:admin?) %>
    <%= link_to 'Edit', edit_pet_shop_path(pet_shops), class: 'btn btn-warning' %>
    <%= link_to 'Destroy', pet_shops, class: 'btn btn-danger' , method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
</div>
<div class='animal_box'>
  <div class="top">
    <div>
      <button class='btn btn-default show-contacts'>More</button>
      <% if current_user.try(:admin?) || current_user?(pet_shops.user) %>
      
      <% end %>
    </div>

  </div>

  <div class="bottom">

    <table class="table table-striped">
      <tr>
        <td><b>Title:</b></td>
        <td><%= pet_shops.title %></td>
      </tr>
      <tr>
        <td><b>Phone:</b></td>
        <td><%= pet_shops.phone %></td>
      </tr>
      <tr>
        <td><b>Website:</b></td>
        <td><%= pet_shops.website %></td>
      </tr>
      <tr>
        <td><b>City:</b></td>
        <td><%= pet_shops.city %></td>
      </tr>
      <tr>
        <td><b>Description:</b></td>
        <td><%= pet_shops.description %></td>
      </tr>
      
    </table>
  </div>
</div>     
<% end %>

missing-paws/app/views/pet_shops/new.html.erb
<h1>New Pet Shop</h1>

<%= render 'form' %>

<%= link_to 'Back', pet_shops_path %>

missing-paws/app/views/pet_shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @pet_shop.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pet_shop.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @pet_shop.image_url %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @pet_shop.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @pet_shop.website %>
</p>

<p>
  <strong>City:</strong>
  <%= @pet_shop.city %>
</p>

<%= link_to 'Edit', edit_pet_shop_path(@pet_shop) %> |
<%= link_to 'Back', pet_shops_path %>